#include <iostream>
#include <ctime>
#include <cmath>
#include <functional>
#include <cstdio>
#include <array>
#include <iterator>
#include <string.h>
#include <vector>
#include <algorithm>
#include <cstring>
#include <limits>
#include <stdio.h>
#include <cstdint>
#include <fstream>
#include <cstdlib>
#include <sstream>
#include <string>
#include <malloc.h>
#include <time.h>
#include <cstring>
#include <stdlib.h>
#include <sys/types.h>
#include <dirent.h>
#include <random>
using namespace std;